import { Router } from 'express';
import { requireAuth } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import { placeBetSchema } from '../validators/bet.js';
import { checkBetLimits } from '../middleware/responsibleGaming.js';
import { enforceRiskCheck } from '../middleware/risk.js';
import * as ctrl from '../controllers/bets.js';
const r = Router();
r.use(requireAuth);
r.post('/', validate(placeBetSchema), enforceRiskCheck('bet'), checkBetLimits, ctrl.place);
r.get('/:id', ctrl.getById);
export default r;
