import { Router } from 'express';
import { requireAuth } from '../middleware/auth.js';
import { validate } from '../middleware/validate.js';
import { depositSchema, withdrawSchema } from '../validators/transaction.js';
import { checkDepositLimits, enforceResponsibleGaming } from '../middleware/responsibleGaming.js';
import { enforceRiskCheck } from '../middleware/risk.js';
import { requireKycForWithdrawal } from '../middleware/kycGate.js';
import * as ctrl from '../controllers/transactions.js';
const r = Router();
r.use(requireAuth);
r.post('/deposit', validate(depositSchema), enforceRiskCheck('deposit'), checkDepositLimits, ctrl.deposit);
r.post('/withdraw', validate(withdrawSchema), requireKycForWithdrawal(), enforceRiskCheck('withdraw'), enforceResponsibleGaming('withdraw'), ctrl.withdraw);
export default r;
