import RiskSignal, { SIGNAL_CATEGORY, SIGNAL_SEVERITY } from '../models/RiskSignal.js';

export const SIGNAL_CODES = {
  RAPID_REGISTRATION: 'RISK_RAPID_REGISTRATION',
  MULTIPLE_ACCOUNTS_SAME_DEVICE: 'RISK_MULTIPLE_ACCOUNTS_SAME_DEVICE',
  MULTIPLE_ACCOUNTS_SAME_IP: 'RISK_MULTIPLE_ACCOUNTS_SAME_IP',
  KYC_FAILURES: 'RISK_KYC_FAILURES',
  KYC_MISMATCH: 'RISK_KYC_MISMATCH',
  SUSPICIOUS_ACCOUNT_CHANGE: 'RISK_SUSPICIOUS_ACCOUNT_CHANGE',
  REPEATED_FAILED_LOGIN: 'RISK_REPEATED_FAILED_LOGIN',
  UNUSUAL_LOGIN_VELOCITY: 'RISK_UNUSUAL_LOGIN_VELOCITY',
  UNUSUAL_IP_CHANGE: 'RISK_UNUSUAL_IP_CHANGE',
  SESSION_ANOMALY: 'RISK_SESSION_ANOMALY',
  HIGH_DEPOSIT_VELOCITY: 'RISK_HIGH_DEPOSIT_VELOCITY',
  DEPOSIT_FAILED_REPEATED: 'RISK_DEPOSIT_FAILED_REPEATED',
  UNUSUAL_DEPOSIT_AMOUNT: 'RISK_UNUSUAL_DEPOSIT_AMOUNT',
  DEPOSIT_VELOCITY_SPIKE: 'RISK_DEPOSIT_VELOCITY_SPIKE',
  DEPOSIT_WITHDRAWALRAPID: 'RISK_RAPID_DEPOSIT_WITHDRAWAL',
  MULTIPLE_PAYMENT_INSTRUMENTS: 'RISK_MULTIPLE_PAYMENT_INSTRUMENTS',
  RAPID_WITHDRAWAL_AFTER_DEPOSIT: 'RISK_RAPID_WITHDRAWAL_AFTER_DEPOSIT',
  WITHDRAWAL_FAILURES: 'RISK_WITHDRAWAL_FAILURES',
  UNUSUAL_WITHDRAWAL_AMOUNT: 'RISK_UNUSUAL_WITHDRAWAL_AMOUNT',
  RESTRICTION_BEFORE_WITHDRAWAL: 'RISK_RESTRICTION_BEFORE_WITHDRAWAL',
  UNUSUAL_BALANCE_CHANGE: 'RISK_UNUSUAL_BALANCE_CHANGE',
  ADMIN_BALANCE_ADJUSTMENTS: 'RISK_ADMIN_BALANCE_ADJUSTMENTS',
  TRANSACTION_REVERSAL: 'RISK_TRANSACTION_REVERSAL',
  RECONCILIATION_MISMATCH: 'RISK_RECONCILIATION_MISMATCH',
  PLAYER_BET: 'player.bet',
  PLAYER_GAME_ROUND: 'player.game_round',
  PLAYER_DEPOSIT: 'player.deposit',
  PLAYER_WITHDRAWAL: 'player.withdrawal',
  PLAYER_KYC_RESULT: 'player.kyc_result',
  PLAYER_LOGIN: 'player.login',
  PLAYER_ACCOUNT_CHANGE: 'player.account_change',
};

export const SIGNAL_SEVERITY_MAP = {
  [SIGNAL_CODES.RAPID_REGISTRATION]: SIGNAL_SEVERITY.MEDIUM,
  [SIGNAL_CODES.MULTIPLE_ACCOUNTS_SAME_DEVICE]: SIGNAL_SEVERITY.HIGH,
  [SIGNAL_CODES.MULTIPLE_ACCOUNTS_SAME_IP]: SIGNAL_SEVERITY.HIGH,
  [SIGNAL_CODES.KYC_FAILURES]: SIGNAL_SEVERITY.MEDIUM,
  [SIGNAL_CODES.KYC_MISMATCH]: SIGNAL_SEVERITY.HIGH,
  [SIGNAL_CODES.SUSPICIOUS_ACCOUNT_CHANGE]: SIGNAL_SEVERITY.MEDIUM,
  [SIGNAL_CODES.REPEATED_FAILED_LOGIN]: SIGNAL_SEVERITY.MEDIUM,
  [SIGNAL_CODES.UNUSUAL_LOGIN_VELOCITY]: SIGNAL_SEVERITY.MEDIUM,
  [SIGNAL_CODES.UNUSUAL_IP_CHANGE]: SIGNAL_SEVERITY.LOW,
  [SIGNAL_CODES.SESSION_ANOMALY]: SIGNAL_SEVERITY.LOW,
  [SIGNAL_CODES.HIGH_DEPOSIT_VELOCITY]: SIGNAL_SEVERITY.HIGH,
  [SIGNAL_CODES.DEPOSIT_FAILED_REPEATED]: SIGNAL_SEVERITY.MEDIUM,
  [SIGNAL_CODES.UNUSUAL_DEPOSIT_AMOUNT]: SIGNAL_SEVERITY.MEDIUM,
  [SIGNAL_CODES.DEPOSIT_VELOCITY_SPIKE]: SIGNAL_SEVERITY.HIGH,
  [SIGNAL_CODES.DEPOSIT_WITHDRAWALRAPID]: SIGNAL_SEVERITY.HIGH,
  [SIGNAL_CODES.MULTIPLE_PAYMENT_INSTRUMENTS]: SIGNAL_SEVERITY.MEDIUM,
  [SIGNAL_CODES.RAPID_WITHDRAWAL_AFTER_DEPOSIT]: SIGNAL_SEVERITY.HIGH,
  [SIGNAL_CODES.WITHDRAWAL_FAILURES]: SIGNAL_SEVERITY.MEDIUM,
  [SIGNAL_CODES.UNUSUAL_WITHDRAWAL_AMOUNT]: SIGNAL_SEVERITY.MEDIUM,
  [SIGNAL_CODES.RESTRICTION_BEFORE_WITHDRAWAL]: SIGNAL_SEVERITY.HIGH,
  [SIGNAL_CODES.UNUSUAL_BALANCE_CHANGE]: SIGNAL_SEVERITY.MEDIUM,
  [SIGNAL_CODES.ADMIN_BALANCE_ADJUSTMENTS]: SIGNAL_SEVERITY.LOW,
  [SIGNAL_CODES.TRANSACTION_REVERSAL]: SIGNAL_SEVERITY.HIGH,
  [SIGNAL_CODES.RECONCILIATION_MISMATCH]: SIGNAL_SEVERITY.HIGH,
};

export const SIGNAL_CATEGORY_MAP = {
  [SIGNAL_CODES.RAPID_REGISTRATION]: SIGNAL_CATEGORY.ACCOUNT,
  [SIGNAL_CODES.MULTIPLE_ACCOUNTS_SAME_DEVICE]: SIGNAL_CATEGORY.ACCOUNT,
  [SIGNAL_CODES.MULTIPLE_ACCOUNTS_SAME_IP]: SIGNAL_CATEGORY.ACCOUNT,
  [SIGNAL_CODES.KYC_FAILURES]: SIGNAL_CATEGORY.KYC,
  [SIGNAL_CODES.KYC_MISMATCH]: SIGNAL_CATEGORY.KYC,
  [SIGNAL_CODES.SUSPICIOUS_ACCOUNT_CHANGE]: SIGNAL_CATEGORY.ACCOUNT,
  [SIGNAL_CODES.REPEATED_FAILED_LOGIN]: SIGNAL_CATEGORY.AUTHENTICATION,
  [SIGNAL_CODES.UNUSUAL_LOGIN_VELOCITY]: SIGNAL_CATEGORY.AUTHENTICATION,
  [SIGNAL_CODES.UNUSUAL_IP_CHANGE]: SIGNAL_CATEGORY.AUTHENTICATION,
  [SIGNAL_CODES.SESSION_ANOMALY]: SIGNAL_CATEGORY.AUTHENTICATION,
  [SIGNAL_CODES.HIGH_DEPOSIT_VELOCITY]: SIGNAL_CATEGORY.DEPOSIT,
  [SIGNAL_CODES.DEPOSIT_FAILED_REPEATED]: SIGNAL_CATEGORY.DEPOSIT,
  [SIGNAL_CODES.UNUSUAL_DEPOSIT_AMOUNT]: SIGNAL_CATEGORY.DEPOSIT,
  [SIGNAL_CODES.DEPOSIT_VELOCITY_SPIKE]: SIGNAL_CATEGORY.DEPOSIT,
  [SIGNAL_CODES.DEPOSIT_WITHDRAWALRAPID]: SIGNAL_CATEGORY.FINANCIAL,
  [SIGNAL_CODES.MULTIPLE_PAYMENT_INSTRUMENTS]: SIGNAL_CATEGORY.DEPOSIT,
  [SIGNAL_CODES.RAPID_WITHDRAWAL_AFTER_DEPOSIT]: SIGNAL_CATEGORY.WITHDRAWAL,
  [SIGNAL_CODES.WITHDRAWAL_FAILURES]: SIGNAL_CATEGORY.WITHDRAWAL,
  [SIGNAL_CODES.UNUSUAL_WITHDRAWAL_AMOUNT]: SIGNAL_CATEGORY.WITHDRAWAL,
  [SIGNAL_CODES.RESTRICTION_BEFORE_WITHDRAWAL]: SIGNAL_CATEGORY.WITHDRAWAL,
  [SIGNAL_CODES.UNUSUAL_BALANCE_CHANGE]: SIGNAL_CATEGORY.FINANCIAL,
  [SIGNAL_CODES.ADMIN_BALANCE_ADJUSTMENTS]: SIGNAL_CATEGORY.FINANCIAL,
  [SIGNAL_CODES.TRANSACTION_REVERSAL]: SIGNAL_CATEGORY.FINANCIAL,
  [SIGNAL_CODES.RECONCILIATION_MISMATCH]: SIGNAL_CATEGORY.FINANCIAL,
};

export async function createSignal(playerId, code, options = {}) {
  const {
    brandId = null,
    jurisdictionId = null,
    description = '',
    sourceEvent = '',
    eventData = {},
    metadata = {},
    dedupWindowMs = 60 * 60 * 1000,
  } = options;

  const severity = SIGNAL_SEVERITY_MAP[code] || SIGNAL_SEVERITY.LOW;
  const category = SIGNAL_CATEGORY_MAP[code] || SIGNAL_CATEGORY.ACCOUNT;

  if (dedupWindowMs > 0 && sourceEvent) {
    const since = new Date(Date.now() - dedupWindowMs);
    const existing = await RiskSignal.findOne({
      playerId,
      code,
      sourceEvent,
      createdAt: { $gte: since },
    }).lean();
    if (existing) return existing;
  }

  return RiskSignal.create({
    playerId,
    brandId,
    jurisdictionId,
    code,
    category,
    severity,
    description,
    sourceEvent,
    eventData,
    metadata,
  });
}

export async function getSignalsForPlayer(playerId, options = {}) {
  const { category, severity, limit = 50, processed = null } = options;
  const query = { playerId };
  if (category) query.category = category;
  if (severity) query.severity = severity;
  if (processed !== null) query.processed = processed;
  return RiskSignal.find(query).sort({ createdAt: -1 }).limit(limit);
}

export async function getRecentSignals(playerId, hours = 24) {
  const since = new Date(Date.now() - hours * 60 * 60 * 1000);
  return RiskSignal.find({ playerId, createdAt: { $gte: since } }).sort({ createdAt: -1 });
}

export async function countSignalsByCategory(playerId, hours = 24) {
  const since = new Date(Date.now() - hours * 60 * 60 * 1000);
  return RiskSignal.aggregate([
    { $match: { playerId, createdAt: { $gte: since } } },
    { $group: { _id: '$category', count: { $sum: 1 } } },
  ]);
}

export async function countSignalsByCode(playerId, code, hours = 24) {
  const since = new Date(Date.now() - hours * 60 * 60 * 1000);
  return RiskSignal.countDocuments({ playerId, code, createdAt: { $gte: since } });
}

export async function markSignalProcessed(signalId) {
  return RiskSignal.findByIdAndUpdate(signalId, { processed: true, processedAt: new Date() }, { new: true });
}

export async function getSignalStats(brandId = null, jurisdictionId = null) {
  const match = {};
  if (brandId) match.brandId = brandId;
  if (jurisdictionId) match.jurisdictionId = jurisdictionId;

  return RiskSignal.aggregate([
    { $match: match },
    {
      $group: {
        _id: { category: '$category', severity: '$severity' },
        count: { $sum: 1 },
      },
    },
  ]);
}
